services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ${DB_FOLDER}:/var/lib/postgresql/data
    expose:
      - "5432"
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - postgres

  room_manager:
    build: ./backend
    command: python -u room_manager.py
    expose:
      - "5000"
    environment:
      - GAMES_API_URL=${GAMES_API_URL}
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./backend/.logs:/app/.logs
    depends_on:
      - postgres

  game_manager:
    build: ./backend
    command: python -u game_manager.py
    expose:
      - "5001"
    environment:
      - LOBBY_API_URL=${LOBBY_API_URL}
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./backend/.logs:/app/.logs
    depends_on:
      - postgres

  frontend:
    build: ./client
    depends_on:
      - room_manager
      - game_manager
